component/zeebe:
  - changed-files:
    - any-glob-to-any-file:
        - '.ci/docker/test/*'
        - '.github/ISSUE_TEMPLATE/zeebe-*'
        - '.github/actions/**'
        - '.github/renovate.json'
        - '.github/workflows/zeebe-*'
        - 'Dockerfile'
        - 'bom/*'
        - 'build-tools/**'
        - 'camunda.Dockerfile'
        - 'clients/**'
        - 'dist/**'
        - 'monitor/**'
        - 'parent/*'
        - 'pom.xml'
        - 'spring-boot-starter-camunda-sdk/**'
        - 'zeebe/**'
component/operate:
  - changed-files:
    - any-glob-to-any-file:
        - '.ci/docker/test/*'
        - '.github/ISSUE_TEMPLATE/operate-*'
        - '.github/actions/**'
        - '.github/renovate.json'
        - '.github/workflows/operate-*'
        - 'bom/*'
        - 'camunda.Dockerfile'
        - 'dist/**'
        - 'operate.Dockerfile'
        - 'operate/**'
        - 'parent/*'
        - 'pom.xml'
        - 'webapps-common/**'
component/identity:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/identity-*'
          - 'camunda.Dockerfile'
          - 'identity/**'
component/tasklist:
  - changed-files:
      - any-glob-to-any-file:
          - '.ci/docker/test/*'
          - '.github/ISSUE_TEMPLATE/tasklist-*'
          - '.github/actions/**'
          - '.github/renovate.json'
          - '.github/workflows/tasklist-*'
          - 'bom/*'
          - 'camunda.Dockerfile'
          - 'dist/**'
          - 'parent/*'
          - 'pom.xml'
          - 'tasklist/**'
          - 'tasklist.Dockerfile'
          - 'webapps-common/**'
component/build-pipeline:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/actions/**'
          - '.github/workflows/**'
          - '.github/actionlint*'
          - 'maven-settings.xml'
