---
name: Setup Yarn Cache


description: Configured GHA cache for Yarn global cache dir (no save on PRs), see https://github.com/camunda/camunda/wiki/CI-&-Automation#caching-strategy

inputs:
  directory:
    description: Directory of the project for which Yarn to GHA cache should be configured
    required: true

runs:
  using: composite
  steps:
  - name: Get Yarn global cache directory
    shell: bash
    working-directory: ${{ inputs.directory }}
    run: |
      yarn_version=$(yarn --version)
      echo "yarn version: $yarn_version"

      if [[ $yarn_version == 1* ]]; then
        echo "Yarn version 1.x"
        yarn cache dir || true
        echo "CUSTOM_YARN_GLOBAL_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV
      else
        echo "Yarn version 2.x?"
        yarn config get cacheFolder || true
        echo "CUSTOM_YARN_GLOBAL_CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_ENV
      fi

  - name: Save global Yarn cache on non-PRs
    if: startsWith(github.ref_name, 'stable') || github.ref_name == 'main'
    uses: actions/cache@v4
    with:
      # need to use an environment variable here, thx to https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7415
      path: "${{ env.CUSTOM_YARN_GLOBAL_CACHE_DIR }}"
      # it matters for caching as absolute paths on self-hosted and Github runners differ
      # self-hosted: `/runner/` vs gh-hosted: `/home/runner`
      key: ${{ runner.environment }}-${{ runner.os }}-yarn-${{ hashFiles(format('{0}/yarn.lock', inputs.directory)) }}
      restore-keys: |
        ${{ runner.environment }}-${{ runner.os }}-yarn

  - name: Restore global Yarn cache always
    # Restore cache (but don't save it) if we're not on main or stable/* branches
    if: ${{ !(startsWith(github.ref_name, 'stable') || github.ref_name == 'main') }}
    uses: actions/cache/restore@v4
    with:
      path: "${{ env.CUSTOM_YARN_GLOBAL_CACHE_DIR }}"
      key: ${{ runner.environment }}-${{ runner.os }}-yarn-${{ hashFiles(format('{0}/yarn.lock', inputs.directory)) }}
      restore-keys: |
        ${{ runner.environment }}-${{ runner.os }}-yarn
