name: Build Tasklist FE
description: Builds the Tasklist frontend

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Setup yarn
      run: npm install -g yarn
      shell: bash
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - uses: ./.github/actions/setup-yarn-cache
      with:
        directory: ${{ inputs.directory }}
    - name: Install node dependencies
      working-directory: ./tasklist/client
      shell: bash
      run: yarn
    - name: Build frontend
      working-directory: ./tasklist/client
      run: yarn build
      shell: bash
