name: "test c8run on linux"

on:
  push:
    paths:
      - "c8run/**"
      - ".github/workflows/c8run-linux-x86-build.yaml"

jobs:
  test_c8run:
    name: Test deploying camunda platform on c8run
    runs-on: ubuntu-latest
    steps:

      - name: disable and stop mono-xsp4.service
        run: |
             sudo systemctl stop mono-xsp4.service || true
             sudo systemctl disable mono-xsp4.service || true
             sudo killall mono || true
             sudo killall xsp4 || true

      - uses: actions/checkout@v4

      - name: print architecture
        run: arch

      - name: make a package
        run: ./package.sh
        working-directory: ./c8run

      - name: Run c8run
        run: nohup ./start.sh --detached
        working-directory: ./c8run
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-21-jdk-amd64

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./c8run/e2e_tests

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./c8run/e2e_tests

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./c8run/e2e_tests

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./c8run/e2e_tests/playwright-report
          retention-days: 30

      - uses: actions/upload-artifact@v4
        with:
          name: camunda8-run-build
          path: ./c8run/camunda8-run*
          retention-days: 1

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: c8run-logs
          path: ./c8run/log/*.log
          retention-days: 10
