name: Optimize Commands Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  optimize-commands-dispatch:
    if: ${{ contains(github.event.issue.labels.*.name, 'component/optimize') }}
    name: Dispatch Command
    runs-on: ubuntu-latest
    steps:
      - name: Create URL to the run output
        id: vars
        run: |
          {
            echo "run_url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          } >> "$GITHUB_OUTPUT"

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GH_PROJECT_AUTOMATION_TOKEN }}
          permission: none
          commands: |
            assign
            eng
            help
            pm
            qa

      - name: Update comment in case of failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > Had issues fulfilling your command, check the [logs](${{ steps.vars.outputs.run_url }})
          reactions: confused
