name: Optimize Backend Linting
on:
  push:
    branches:
      - main
      - maintenance/**
      - release/**
    paths:
      - "optimize/**"
      - ".github/workflows/optimize-code-scanning-java.yml"
    paths-ignore:
      - "optimize/client/**"
  pull_request:
    paths:
      - "optimize/**"
      - ".github/workflows/optimize-code-scanning-java.yml"
    paths-ignore:
      - "optimize/client/**"
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Fetch main branch
        run: git fetch origin main:refs/remote/origin/main

      - name: Setup Java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: "adopt"
          java-version: "21"

      - name: Check Google Java codestyle
        run: mvn -q spotless:check
