name: Optimize Opened Issues Automation
on:
  issues:
    types: [opened]
jobs:
  optimize-opened-issues-automation:
    name: Opened Issues Automation
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'component/optimize')
    steps:
      - name: Create variables
        id: vars
        run: |
          {
            echo "project_id=101"
            echo "qa_engineer=RobertDorlan"
          } >> "$GITHUB_OUTPUT"

      - name: Assign issue to the project
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PROJECT_AUTOMATION_TOKEN }}
        run: |
          issue_url=${{ github.event.issue.html_url }}
          project_id=${{ steps.vars.outputs.project_id }}
          gh project item-add $project_id --url $issue_url --owner ${{ github.event.repository.owner.login }}

      - name: Assign QA
        if: contains(github.event.issue.labels.*.name, 'kind/bug')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PROJECT_AUTOMATION_TOKEN }}
        run: |
          gh issue edit ${{ github.event.issue.html_url }} --remove-assignee ""
          sleep 2  # avoiding race condition between two commands
          gh issue edit ${{ github.event.issue.html_url }} --add-assignee ${{ steps.vars.outputs.qa_engineer }}

      - name: Update Status field - On Hold
        uses: github/update-project-action@main
        if: contains(github.event.issue.labels.*.name, 'kind/bug')
        with:
          github_token: ${{ secrets.GH_PROJECT_AUTOMATION_TOKEN }}
          organization: ${{ github.event.organization.login }}
          project_number: ${{ steps.vars.outputs.project_id }}
          content_id: ${{ github.event.issue.node_id }}
          field: Status
          value: "On Hold"
